services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.3@sha256:fa3f1a641a265216066676950d5eecdf506955a7bafe2f01996135ae93115cd5
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    network_mode: host
    env_file: /opt/docker/secrets.env
    environment:
      PERIPHERY_ROOT_DIRECTORY: /etc/komodo
      PERIPHERY_ALLOWED_IPS: 172.16.10.18
      PERIPHERY_CORE_PUBLIC_KEYS: "MCowBQYDK2VuAyEA/LCYwDiBxrMYOZdqbntwPoIPHZ7CKpCAOmQQT6JnOyA="
      PERIPHERY_SSL_ENABLED: true
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_LOGGING_LEVEL: "warn"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo:rw
      - /etc/komodo/keys:/config/keys:rw
      - /opt/docker:/opt/docker:rw

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"