user nginx;
worker_processes auto;
worker_rlimit_nofile 10240;

events {
    use epoll;
    multi_accept on;
    worker_connections  4096;
}

http {
  resolver 127.0.0.11 ipv6=off;
  server_tokens off;

  # Extend Bucket-Size for Server-Names
  server_names_hash_bucket_size 64;
  # Default Mime-Types
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  # Real-IP-Settings
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;

  include /etc/nginx/conf.d/*.conf;
}

## LDAPS TLS Stream

stream {
  server {
      listen 636 ssl;
      server_name ldap.srv.seifert.dev;

      # SSL/TLS Certificate & Key for LDAPS termination
      ssl_certificate /etc/letsencrypt/live/auth.seifert.dev/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/auth.seifert.dev/privkey.pem;

      # Optional: Force specific TLS versions
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;

      # Forward traffic to your backend LDAP server (e.g., Active Directory or OpenLDAP)
      proxy_pass lldap:3890;

      # Enable SSL/TLS for the connection to the backend server
      proxy_ssl off;

  }
}