services:
  pangolin:
    image: fosrl/pangolin:ee-postgresql-1.17.1@sha256:67628f0cb66165ebac4634d88577559810d1310bdd5d390e2da2bc5731555ae1
    container_name: pangolin
    depends_on:
      geoipupdate:
        condition: service_healthy
      pangolin-db:
        condition: service_healthy
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    volumes:
      - /opt/docker/pangolin/config:/app/config
      - /opt/docker/geoip:/app/geoip
    healthcheck:
      interval: 10s
      retries: 15
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3001/api/v1/
      timeout: 10s
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gerbil:
    image: fosrl/gerbil:1.3.1@sha256:b16a722d5603fa74acd3e1deb86cea0b8330d015ab5325dc41e44108fe6f29c9
    container_name: gerbil
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 21820:21820/udp
      - 51820:51820/udp
      - 443:443
      - 80:80
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - /opt/docker/gerbil/config:/var/config
    depends_on:
      pangolin:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ip", "link", "show", "wg0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    logging: *default-logging

  # Config Generator for Blocky
  traefik-config-generator:
    image: alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    container_name: traefik-config-generator
    restart: always
    env_file:
      - /opt/docker/secrets.env
    volumes:
      - /opt/docker/traefik/config/dynamic/:/mnt/config/
    command: >
      sh -c "apk add --no-cache gettext >/dev/null && 
             envsubst < /mnt/config/dynamic_config.yml.template > /mnt/config/dynamic_config.yml &&
             chown 1000:1000 /mnt/config/dynamic_config.yml &&
             echo 'Config generiert, schlafe jetzt...' &&
             sleep infinity"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /mnt/config/dynamic_config.yml ] || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  traefik:
    image: traefik:v3.6.14@sha256:4cda3393930dceff030e144b46260e96e1337c9cfaa4fed81c90cb8f4d498f57
    container_name: traefik
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
      pangolin:
        condition: service_healthy
      redis:
        condition: service_healthy
      traefik-config-generator:
        condition: service_healthy
    network_mode: service:gerbil
    env_file: /opt/docker/secrets.env
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}  # Cloudflare ACME API TOKEN
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${SECRET_ADMIN_EMAIL}
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/docker/traefik/config/traefik_config.yml:/etc/traefik/traefik_config.yml
      - /opt/docker/traefik/config/dynamic/dynamic_config.yml:/etc/traefik/dynamic/dynamic_config.yml
      - /opt/docker/traefik/config/sites/captcha.html:/etc/traefik/sites/captcha.html
      - /opt/docker/traefik/config/sites/ban.html:/etc/traefik/sites/ban.html
      - /opt/docker/traefik/letsencrypt:/letsencrypt
      - /opt/docker/traefik/geoblock:/var/lib/geoblock
      - /var/log/traefik:/var/log/traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    logging: *default-logging

  redis:
    image: redis:8.6.2-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    logging: *default-logging

  pangolin-db:
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    container_name: pangolin-db
    restart: unless-stopped
    shm_size: '1gb'
    env_file: /opt/docker/secrets.env
    environment:
      - POSTGRES_USER=pangolin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=pangolin
    volumes:
      - pangolin-pgdata:/var/lib/postgresql
    command: >
      postgres
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c work_mem=8MB
      -c maintenance_work_mem=128MB
      -c min_wal_size=512MB
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
      -c synchronous_commit=off
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_worker_processes=2
      -c max_parallel_workers_per_gather=1
      -c max_parallel_workers=2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pangolin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    logging: *default-logging

  # https://docs.pangolin.net/self-host/community-guides/geolite2automation
  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:v7.1.1@sha256:faecdca22579730ab0b7dea5aa9af350bb3c93cb9d39845c173639ead30346d2
    container_name: geoipupdate
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}         # Account ID
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}       # API key
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-ASN    # Which dbs should be downloaded
      GEOIPUPDATE_FREQUENCY: 72                                 # Update intervall in hours
    volumes:
      - '/opt/docker/geoip/GeoLite2:/usr/share/GeoIP'
    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/share/GeoIP/GeoLite2-Country.mmdb || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.7@sha256:6ca53ad26196ca59ddd4fa692a586b73d8fcde085046163b9ca2f04887dca563
    container_name: crowdsec
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      DISABLE_LOCAL_API: true
      LOCAL_API_URL: ${CROWDSEC_LAPI_URL}                   # Crowdsec Central LAPI URL https://example.com:8443
      AGENT_USERNAME: ${CROWDSEC_LAPI_USERNAME}             # Crowdsec Maschine Username
      AGENT_PASSWORD: ${CROWDSEC_LAPI_PASSWORD}             # Crowdsec Maschine Password
      COLLECTIONS: crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/traefik
      ENROLL_TAGS: docker
      GID: "1000"
      PARSERS: crowdsecurity/whitelists
    volumes:
      - /opt/docker/crowdsec/config:/etc/crowdsec
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7422/ || [ $? -ne 7 ]"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging: *default-logging

volumes:
  pangolin-pgdata:

networks:
  default:
    driver: bridge
    enable_ipv6: true
    name: pangolin
