services:
  # Nginx Reverse Proxy - https://github.com/nginx/nginx
  nginx:
    image: nginx:1.30.0-alpine@sha256:f60d139a69209d4340f6621fc6a50c9843702214231522a3390432f8db0ed870
    container_name: nginx
    depends_on:
      blocky:
        condition: service_healthy
      certbot:
        condition: service_healthy
    env_file: /opt/docker/secrets.env
    environment:
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
      - NGINX_ENVSUBST_FILTERED_VAR_NAMES=SECRET_DOMAIN SECRET_CERT_NAME
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/certbot/certs/live/${SECRET_CERT_NAME}:/etc/letsencrypt/live/node-cert:ro
      - /opt/docker/certbot/certs/archive:/etc/letsencrypt/archive:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Certbot - https://github.com/cloudflare/certbot-dns-cloudflare
  certbot:
    image: certbot/dns-cloudflare:v5.5.0@sha256:f90db06a98b61bd221fe5a9688d0bb975b444760ef677cb4369ffc2a8a16e579
    container_name: certbot
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file: /opt/docker/secrets.env
    environment:
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/certbot/certs:/etc/letsencrypt
      - /opt/docker/certbot/cloudflare.ini:/cloudflare.ini:ro
      - /opt/docker/certbot/certbot-entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "openssl x509 -checkend 86400 -noout -in /etc/letsencrypt/live/${SECRET_CERT_NAME}/fullchain.pem || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    logging: *default-logging

  # Config Generator for Blocky
  blocky-config-generator:
    image: alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    container_name: blocky-config-generator
    restart: always
    env_file:
      - /opt/docker/secrets.env
    volumes:
      - /opt/docker/blocky/config.yml.template:/tmp/config.yml.template:ro
      - blocky-config-vol:/mnt/config
    command: >
      sh -c "apk add --no-cache gettext >/dev/null && 
             envsubst < /tmp/config.yml.template > /mnt/config/config.yml &&
             chown 100:100 /mnt/config/config.yml &&
             echo 'Config generiert, schlafe jetzt...' &&
             sleep infinity"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /mnt/config/config.yml ] || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.29.0@sha256:a6d99f323d3036a99a3767a52ad612f4d8f3f31167492bfc14d4ea57b24cdfd0
    container_name: blocky
    depends_on:
      blocky-config-generator:
        condition: service_healthy
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    volumes:
      - blocky-config-vol:/app
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "4000:4000/tcp"
    logging: *default-logging

  blocky-redis:
    image: redis:8.6-alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
    container_name: blocky-redis
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --bind 0.0.0.0
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
      --save "" 
      --appendonly no
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging
  
  blocky-postgres:
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    container_name: blocky-postgres
    shm_size: '1gb'
    restart: unless-stopped
    command: >
      postgres 
      -c shared_buffers=512MB 
      -c work_mem=128MB 
      -c maintenance_work_mem=256MB 
      -c effective_cache_size=2GB 
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    env_file: /opt/docker/secrets.env
    environment:
      - POSTGRES_USER=blocky
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=blocky_logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blocky -d blocky_logs"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

volumes:
  redis_data:
  pgdata:
  blocky-config-vol: