localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false
silenceTrashConflictWarnings: true

customFormatDefinitions:
  - trash_id: custom-size-more-50gb
    trash_scores:
      default: -10000
    trash_description: "Size: Block sizes over 50GB"
    name: "Size: Block More 50GB"
    includeCustomFormatWhenRenaming: false
    specifications:
      - name: "Size"
        implementation: SizeSpecification
        negate: true
        required: true
        fields:
          min: 0
          max: 50
      - name: "Size"
        implementation: SizeSpecification
        negate: true
        required: true
        fields:
          min: 0
          max: 50

radarr:
  Radarr:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    
    quality_profiles:
      - name: "[German] UHD Bluray + WEB (Alternative)"
        min_format_score: 10000
      - name: "[German] Remux + WEB 2160p"
        min_format_score: 10000
      - name: "[German] Anime HD Bluray + WEB"
        min_format_score: 10000
    
    custom_formats:
      - trash_ids:
          # Video Formats
          - 493b6d1dbec3c3364c59d7607f7e3405 # HDR Formats - HDR
          - caa37d0df9c348912df1fb1d88f9273a # HDR Formats - HDR10+ Boost
          - b337d6812e06c200ec9a2d3cfa9d20a7 # HDR Formats - DV Boost
          - 923b6abef9b17f937fab56cfcf89e1f1 # HDR Formats - DV (w/o HDR fallback)
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Crierion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # Audio Formats
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
          # Custom Formats
          - custom-size-more-50gb
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
     

  Radarr-List:
    base_url: http://radarr-list:7878
    api_key: !secret RADARR_LIST_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    
    quality_profiles:
      - name: "[German] UHD Bluray + WEB (Alternative)"
        min_format_score: 10000
      - name: "[German] Remux + WEB 2160p"
        min_format_score: 10000
      - name: "[German] Anime HD Bluray + WEB"
        min_format_score: 10000
    
    custom_formats:
      - trash_ids:
          # Video Formats
          - 493b6d1dbec3c3364c59d7607f7e3405 # HDR Formats - HDR
          - caa37d0df9c348912df1fb1d88f9273a # HDR Formats - HDR10+ Boost
          - b337d6812e06c200ec9a2d3cfa9d20a7 # HDR Formats - DV Boost
          - 923b6abef9b17f937fab56cfcf89e1f1 # HDR Formats - DV (w/o HDR fallback)
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Crierion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # Audio Formats
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
          # Custom Formats
          - custom-size-more-50gb
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"

sonarr:
  Sonarr:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY
    include:
      - template: 7324309a7d1e10dc0dc2cea6c70ed852 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 08cececf1840290f6fd490b7d79e8642 # [German] UHD Remux + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: 6fe5937e1dcc2269e23b49eb46dfe6d6 # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    quality_profiles:
      - name: "[German] UHD Bluray + WEB (Alternative)"
        min_format_score: 10000
      - name: "[German] UHD Remux + WEB"
        min_format_score: 10000
      - name: "[German] Anime HD Bluray + WEB"
        min_format_score: 10000
    custom_formats:
      - trash_ids:
          # Video Formats
          - 505d871304820ba7106b693be6fe4a9e # HDR Formats - HDR
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR Formats - HDR10+ Boost
          - 7c3a61a9c6cb04f52f1544be6d44a026 # HDR Formats - DV Boost
          - 9b27ab6498ec0f31a3353992e19434ca # HDR Formats - DV (w/o HDR fallback)
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Crierion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # Audio Formats
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
          - 9d00418ba386a083fbf4d58235fc37ef # DTS X
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
          - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
          - 30f70576671ca933adbdcfc736a69718 # PCM
          - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - 185f1dd7264c4562b9022d963ac37424 # DTS-ES
          - 5964f2a8b3be407d083498e4459d05d0 # DTS
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
          - dbe00161b08a25ac6154c55f95e6318d # DD
          # Streaming Boost
          - 43b3cf48cb385cd3eac608ee6bca7f09 # UHD Streaming Boost
          - 218e93e5702f44a68ad9e3c6ba87d2f0 # HD Streaming Boost
          # Custom Formats
          - custom-size-more-50gb
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] UHD Remux + WEB"
          - name: "[German] Anime HD Bluray + WEB"

