localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

radarr:
  Radarr:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    custom_formats:
      - trash_ids:
          - id: e9a1944a254e6f8a9da63083f7ae15cb # [Audio] Audio Formats https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/audio-formats.json
          - id: 7e1724c5da59e7474803ad25be98f6a3 # [HDR Formats] HDR https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr.json
          - id: 7d366c213e5c23a052b157356fac1921 # [HDR Formats] HDR10+ Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr10-boost.json
          - id: e0b2774083df4265f25c9e5bc6c80940 # [HDR Formats] DV Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-boost.json
          - id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-webdl.json
          - id: 158188097a58d7687dee647e04af0da3 # [Required] Golden Rule HD https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/required-golden-rule-hd.json
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"

  Radarr-List:
    base_url: http://radarr-list:7878
    api_key: !secret RADARR_LIST_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    custom_formats:
      - trash_ids:
          - id: e9a1944a254e6f8a9da63083f7ae15cb # [Audio] Audio Formats https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/audio-formats.json
          - id: 7e1724c5da59e7474803ad25be98f6a3 # [HDR Formats] HDR https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr.json
          - id: 7d366c213e5c23a052b157356fac1921 # [HDR Formats] HDR10+ Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr10-boost.json
          - id: e0b2774083df4265f25c9e5bc6c80940 # [HDR Formats] DV Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-boost.json
          - id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-webdl.json
          - id: 158188097a58d7687dee647e04af0da3 # [Required] Golden Rule HD https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/required-golden-rule-hd.json
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"

sonarr:
  Sonarr:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY
    include:
      - template: 7324309a7d1e10dc0dc2cea6c70ed852 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 08cececf1840290f6fd490b7d79e8642 # [German] UHD Remux + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: 6fe5937e1dcc2269e23b49eb46dfe6d6 # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    custom_format_groups:
      - trash_guide:
          - id: e9a1944a254e6f8a9da63083f7ae15cb # [Audio] Audio Formats https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/audio-formats.json
          - id: 7e1724c5da59e7474803ad25be98f6a3 # [HDR Formats] HDR https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr.json
          - id: 7d366c213e5c23a052b157356fac1921 # [HDR Formats] HDR10+ Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-hdr10-boost.json
          - id: e0b2774083df4265f25c9e5bc6c80940 # [HDR Formats] DV Boost https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-boost.json
          - id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/hdr-formats-dv-webdl.json
          - id: 158188097a58d7687dee647e04af0da3 # [Required] Golden Rule HD https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf-groups/required-golden-rule-hd.json
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"