localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

radarr:
  Radarr:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH
    custom_format_groups:
      # [Audio] Audio Formats - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/audio-formats.json
      - trash_guide:
          - id: 9d5acd8f1da78dfbae788182f7605200
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [HDR Formats] HDR - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/hdr-formats-hdr.json
      - trash_guide:
          - id: ef20e67b95a381fb3bc6d1f06ea24f46
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [HDR Formats] HDR10+ Boost - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/hdr-formats-hdr10-boost.json
      - trash_guide:
          - id: b29413a7487478fe98228ce79e5689e4
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [HDR Formats] DV Boost - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/hdr-formats-dv-boost.json
      - trash_guide:
          - id: 1616617ab3a14397a2b2321bcbda44d1
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [HDR Formats] DV (w/o HDR fallback) - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/hdr-formats-dv-webdl.json
      - trash_guide:
          - id: 7fc2751eef7e6bdc70b74136e5e35c76
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [Release Groups] German - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/release-groups-german.json
      - trash_guide:
          - id: bc85e56ee3bd0f01467866d5f1261543
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
      # [Required] Golden Rule UHD - https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/required-golden-rule-uhd.json
      - trash_guide:
          - id: ff204bbcecdd487d1cefcefdbf0c278d
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
          - name: "[German] Remux + WEB 2160p"
          - name: "[German] Anime HD Bluray + WEB"
    custom_formats:
      # Movie Versions (optional)
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Crierion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
            score: 25
          - name: "[German] Remux + WEB 2160p"
            score: 25
          - name: "[German] Anime HD Bluray + WEB"
            score: 25
      - trash_ids:
          - 957d0f44b592285f26449575e8b1167e # Special Edition
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
            score: 125
          - name: "[German] Remux + WEB 2160p"
            score: 125
          - name: "[German] Anime HD Bluray + WEB"
            score: 125
      - trash_ids:
          - a3d82cbef5039f8d295478d28a887159 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB (Alternative)"
            score: 800
          - name: "[German] Remux + WEB 2160p"
            score: 800
          - name: "[German] Anime HD Bluray + WEB"
            score: 800


  Radarr-List:
    base_url: http://radarr-list:7878
    api_key: !secret RADARR_LIST_API_KEY
    include:
      - template: 425da1ba30711b55d2eb371437ec98d7 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 79faa9943cef2f510b997b1f2a9f3ea6 # [German] Remux + WEB 2160p https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH

sonarr:
  Sonarr:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY
    include:
      - template: 7324309a7d1e10dc0dc2cea6c70ed852 # [German] UHD Bluray + WEB (Alternative) https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 08cececf1840290f6fd490b7d79e8642 # [German] UHD Remux + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-remux-web.json
        source: TRASH
      - template: 6fe5937e1dcc2269e23b49eb46dfe6d6 # [German] Anime HD Bluray + WEB https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-anime-hd-bluray-web.json
        source: TRASH