services:

  # Nginx Reverse Proxy - https://github.com/nginx/nginx
  nginx:
    image: nginx:1.29.8-alpine@sha256:2c4de29ca0588f9b56ced6691e0c605c2fd00501478e2e12949ba062304bc1ca
    container_name: nginx
    env_file: /opt/docker/secrets.env
    labels:
      - "autoheal=true"
    environment:
      - TZ=Europe/Berlin
      - NGINX_ENVSUBST_FILTERED_VAR_NAMES=SECRET_DOMAIN SECRET_CERT_NAME
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/templates:/etc/nginx/templates:ro
      - /opt/docker/nginx/includes:/etc/nginx/includes:ro
      - /opt/docker/certbot/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Certbot - https://github.com/cloudflare/certbot-dns-cloudflare
  certbot:
    image: certbot/dns-cloudflare:v5.5.0@sha256:f90db06a98b61bd221fe5a9688d0bb975b444760ef677cb4369ffc2a8a16e579
    container_name: certbot
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
      - SECRET_CERT_DOMAINS=srv.${SECRET_DOMAIN},*.srv.${SECRET_DOMAIN}
    volumes:
      - /opt/docker/certbot/certs:/etc/letsencrypt
      - /opt/docker/certbot/cloudflare.ini:/cloudflare.ini:ro
      - /opt/docker/certbot/certbot-entrypoint.sh:/entrypoint.sh:ro
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "openssl x509 -checkend 86400 -noout -in /etc/letsencrypt/live/${SECRET_CERT_NAME}/fullchain.pem || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    logging: *default-logging

  # SABnzbd - https://hub.docker.com/r/linuxserver/sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:version-4.5.5@sha256:f0abed8e9450d5b71631a89b663fbfbfbb6909b254f94911c7e77162a3827854
    container_name: sabnzbd
    labels:
      - "autoheal=true"
    volumes:
      - /opt/docker/sabnzbd/config:/config
      - /opt/docker/sabnzbd/scripts:/scripts
      - /mnt/data/usenet:/data/usenet
      - /mnt/download-temp:/incomplete
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - UMASK=002
    networks:
      - arr_network
    expose:
      - 8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Seerr - https://github.com/seerr-team/seerr
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.1.1@sha256:d535391db3b5a22ce02241e6d7a50ca714e75d927e46aa20456b77fa051cbf52
    container_name: seerr
    init: true
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=info
      - PORT=5055
    expose:
      - 5055
    networks:
      - arr_network
    volumes:
      - /opt/docker/seerr/config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5055/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging
    

  # Radarr - https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: linuxserver/radarr:version-6.1.1.10360@sha256:581f159c2b67436863cb4da30e158ef6f6b8878472abbba79ee5d5f7e6b7d28d
    container_name: radarr
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - UMASK=002
    volumes:
      - /opt/docker/radarr/config:/config
      - /mnt/data:/data
    expose:
      - 7878
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Radarr - https://hub.docker.com/r/linuxserver/radarr
  radarr-list:
    image: linuxserver/radarr:version-6.1.1.10360@sha256:581f159c2b67436863cb4da30e158ef6f6b8878472abbba79ee5d5f7e6b7d28d
    container_name: radarr-list
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - UMASK=002
    volumes:
      - /opt/docker/radarr-list/config:/config
      - /mnt/data:/data
    expose:
      - 7878
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Sonarr - https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: linuxserver/sonarr:version-4.0.16.2944@sha256:21c1c3d52248589bb064f5adafec18cad45812d7a01d317472955eef051e619b
    container_name: sonarr
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - UMASK=002
    volumes:
      - /opt/docker/sonarr/config:/config
      - /mnt/data:/data
    expose:
      - 8989
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Prowlarr - Indexer Management - https://github.com/Prowlarr/Prowlarr
  prowlarr:
    image: linuxserver/prowlarr:version-2.3.0.5236@sha256:e50f3b188a7d1771b61f395c4203e35476bd3047683508740305e830e15bacf7
    container_name: prowlarr
    labels:
      - "autoheal=true"
    depends_on:
      - "umlautadaptarr"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
    volumes:
      - /opt/docker/prowlarr/data:/config
    expose:
      - 9696
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging
 
  # VPN Container for qBittorrent with WireGuard and ProtonVPN
  qbittorrent-vpn:
    image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: qbittorrent-vpn
    labels:
      - "autoheal=true"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_PRIVATE_KEY=${QBIT_PROTON_PRIVATE_KEY}
      - WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL=25s
      - SERVER_COUNTRIES=${QBIT_PROTON_COUNTRIES}
      - UPDATER_PROTONVPN_EMAIL=${PROTON_VPN_EMAIL}
      - UPDATER_PROTONVPN_PASSWORD=${PROTON_VPN_PASSWORD}  
      - PORT_FORWARD_ONLY=on
      - UPDATER_PERIOD=24h
      - DNS=1.1.1.1,8.8.8.8
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
    volumes:
      - /opt/docker/qbittorrent-vpn:/gluetun
    expose:
      - 8000 # Gluetun Control Server for Port Forwarding
      - 8080 # qBittorrent WebUI
      - 80   # Speedtest-Tracker
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Torrent Downloader
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1@sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485
    container_name: qbittorrent
    labels:
      - "autoheal=true"
    depends_on:
      qbittorrent-vpn:
        condition: service_healthy
    network_mode: "service:qbittorrent-vpn"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - UMASK=002
      - WEBUI_PORT=8080
    volumes:
      - /opt/docker/qbit:/config
      - /mnt/data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:8080/api/v2/app/version && ping -c1 1.1.1.1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Qbit Torrent WebUI - Automation
  qui:
    image: ghcr.io/autobrr/qui:v1.16.1@sha256:07b6ea9572e52e8b5f70f8fb15a7c688d8d754a7616242d3ad0b21dbd5c05836
    container_name: qui
    labels:
      - "autoheal=true"
    volumes:
      - /opt/docker/qui:/config
      - /mnt/data:/data
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
    expose:
      - 7476
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7476/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging: *default-logging
  
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6.13.6@sha256:e2bf5b593e4e7d699e6242423ad7966190cd52ba8eefafdfdbb0cb5b0b609b96
    container_name: cross-seed
    env_file: /opt/docker/secrets.env
    command: daemon
    user: "3006:3006"
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
    volumes:
      - /opt/docker/cross-seed:/config
      - /mnt/data:/data
    expose:
      - 2468
    networks:
      - arr_network
    restart: unless-stopped
    #healthcheck:
    #  test: ["CMD-SHELL", "ps aux | grep -v grep | grep -q 'cross-seed'"]
    #  interval: 1m
    #  timeout: 10s
    #  retries: 3
    logging: *default-logging

  # Torrent And RSS Automation
  autobrr:
    image: ghcr.io/autobrr/autobrr:v1.76.0@sha256:f0f4d73fcd77700b1c98233562cd94a78b9bf685a7594a0aac4f8a9436b5044d
    container_name: autobrr
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
    volumes:
      - /opt/docker/autobrr:/config
    expose:
      - 7474
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474/api/healthz/liveness"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *default-logging

  # Speedtest-Tracker for Qbit VPN
  speedtest-tracker-qbit:
    image: lscr.io/linuxserver/speedtest-tracker:1.13.12@sha256:eb3d249f16177964daa4fff7f6a90bbf6645f4e23158d92f5cddb133728d0804
    container_name: speedtest-tracker-qbit
    network_mode: "service:qbittorrent-vpn"
    env_file: /opt/docker/secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_KEY=${SPEEDTEST_APP_KEY}
      - APP_URL=${SPEEDTEST_APP_URL}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 */2 * * *
      #- SPEEDTEST_SERVERS=
      - DISPLAY_TIMEZONE=Europe/Berlin #optional
    volumes:
      - /opt/docker/speedtest-tracker:/config
    restart: unless-stopped
    logging: *default-logging

  # Uploader for Private Torrent Trackers (RHD)
  uppollo:
    image: uppollo/uppollo:v1.13.0@sha256:354ff8717b3536333a903939ccde75032d353bda1e9896f8fe1af32733f7fbe2
    container_name: uppollo
    command: serve
    volumes:
      - /opt/docker/uppollo:/home/uppollo/.config/upPollo
      - /data/content:/data/content:ro 
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
    networks:
      - arr_network
    expose:
      - 9999
    restart: unless-stopped
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    logging: *default-logging
    
  configarr:
    container_name: configarr
    hostname: configarr
    image: ghcr.io/raydak-labs/configarr:1.26.0
    environment:
      - TZ=Europe/Berlin
      #- LOG_STACKTRACE=true
    volumes:
      - /opt/docker/configarr/config:/app/config
      - /opt/docker/configarr/repos:/app/repos
      - /opt/docker/configarr/cfs:/app/cfs
      - /opt/docker/configarr/templates:/app/templates
    networks:
      - arr_network
    restart: unless-stopped
    logging: *default-logging

  # MediathekArr - Indexer & Downloader for Mediathek Content - https://github.com/PCJones/MediathekArr
  mediathekarr:
    image: pcjones/mediathekarr:beta@sha256:333f2adbd3d93d196a8a548d2b9b5e70e9172407afc418afcfa5d49ca8c250c9
    container_name: mediathekarr
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - PUID=3006
      - PGID=3006
      - DOWNLOAD_INCOMPLETE_PATH=/data/mediathek/incomplete # Path to incomplete downloads
      - DOWNLOAD_COMPLETE_PATH=/data/mediathek/complete # Path to complete downloads"
    volumes:
      - /opt/docker/mediathekarr:/app/config
      - /mnt/data/mediathek:/data/mediathek # Mount for Mediathek Downloader
    expose:
      - 5007
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5007/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: *default-logging

  # Umlautadaptarr - https://github.com/PCJones/UmlautAdaptarr
  umlautadaptarr:
    image: pcjones/umlautadaptarr:0.7.5@sha256:2c6689d49afe51fcaa5e8a27e139855e0c8782e1e42ec595d8694b74094f991f
    container_name: umlautadaptarr
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=true
      - SONARR__HOST=http://sonarr:8989
      - SONARR__APIKEY=${SONARR_API_KEY}
      - RADARR__ENABLED=true
      - RADARR__HOST=http://radarr:7878
      - RADARR__APIKEY=${RADARR_API_KEY}
    expose:
      - 5006
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5006/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: *default-logging

  # Episeerr - https://github.com/vansmak/episeerr
  episeerr:
    image: vansmak/episeerr:3.6.1@sha256:6553dbb6dad911013ae4c4f7de27b760a6af9b706f964a7fa03cfe93d10ad92b
    container_name: episeerr
    depends_on:
      - "sonarr"
    env_file: /opt/docker/secrets.env
    environment:
      - TZ=Europe/Berlin
      - SONARR_URL=http://sonarr:8989
      - SONARR_API_KEY=${SONARR_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JELLYSEERR_URL=http://seerr:5055
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY}
      - JELLYFIN_URL=https://jellyfin.srv.seifert.dev:8920
      - JELLYFIN_API_KEY=${EPISEERR_JELLYFIN_API_KEY}
      - JELLYFIN_USER_ID=
      - CUSTOMAPP_URL=http://sabnzbd:8080
      - CUSTOMAPP_NAME=SABNZBD
      - CUSTOMAPP_ICON=fas fa-cog
    volumes:
      - /opt/docker/episeerr/config:/app/config
      - /opt/docker/episeerr/logs:/app/logs
      - /opt/docker/episeerr/data:/app/data
      - /opt/docker/episeerr/temp:/app/temp
    expose:
      - 5002
    networks:
      - arr_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: *default-logging

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    container_name: flaresolverr
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TIMEZONE=Europe/Berlin
    networks:
      - arr_network
    expose:
      - 8191
    restart: unless-stopped
    logging: *default-logging

  # Crowdsec AppSec for Arrstack
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.7@sha256:6ca53ad26196ca59ddd4fa692a586b73d8fcde085046163b9ca2f04887dca563
    container_name: crowdsec
    networks:
      - arr_network
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      TZ: Europe/Berlin
      ENROLL_TAGS: docker
      GID: "1000"
      DISABLE_LOCAL_API: true
      LOCAL_API_URL: ${CROWDSEC_LAPI_URL}                   # Crowdsec Central LAPI URL https://example.com:8443
      AGENT_USERNAME: ${CROWDSEC_LAPI_USERNAME}             # Crowdsec Maschine Username
      AGENT_PASSWORD: ${CROWDSEC_LAPI_KEY}             # Crowdsec Maschine Password
      COLLECTIONS: crowdsecurity/linux crowdsecurity/nginx crowdsecurity/base-http-scenarios LePresidente/jellyseerr
      PARSERS: crowdsecurity/whitelists
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
    logging: *default-logging
  
  auto-heal:
    image: willfarrell/autoheal:1.2.0@sha256:31f580ef0279eaced5b38d631b08c474d70d8403c1c2fdd6ddcf2e879d5f3f7c
    container_name: auto-heal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 300
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - arr_network
    logging: *default-logging

volumes:
  tracearr_postgres:
  tracearr_redis:
  tracearr_data:
  thelounge:
  
networks:
  arr_network:
    name: arr_network
    external: false
