# https://docs.pangolin.net/

gerbil:
  start_port: 51820
  base_endpoint: "ztna.seifert.dev"
  subnet_group: "100.89.0.0/16"      # IP address CIDR range for Gerbil exit node subnets.
  block_size: 24                     # Block size for Gerbil exit node CIDR ranges.
  site_block_size: 30                # Block size for site CIDR ranges connected to Gerbil.
  # Org Subnet: 100.90.128.0/24
  # Utility Subnet: 100.96.128.0/24

app:
  dashboard_url: "https://ztna.seifert.dev"
  log_level: "info"
  telemetry:
    anonymous_usage: false

domains:
  domain1:
    base_domain: "seifert.dev"
    cert_resolver: "letsencrypt"
    prefer_wildcard_cert: true

traefik:
  additional_middlewares: ["secured-stack@file"]

postgres:
  connection_string: postgresql://pangolin:WJhs6faswkrugPh5YdsaNGdlGuKsL5HbkV@pangolin-db:5432/pangolin?sslmode=disable

server:
  secret: "Nad5Do/YG+M/3TszyZEBSSEQwOCkhv0DIZ6gn3uTXj7M="
  cors:
    origins: ["https://ztna.seifert.dev"]
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
    allowed_headers: ["X-CSRF-Token", "Content-Type"]
    credentials: false
  maxmind_db_path: "/app/geoip/GeoLite2/GeoLite2-Country.mmdb"
  maxmind_asn_path: "/app/geoip/GeoLite2/GeoLite2-ASN.mmdb"

email:
  smtp_host: "mail.seifert.dev"
  smtp_port: 587
  smtp_user: "notification@seifert.dev"
  smtp_pass: "URDZK2CVNr@Q2Z*t9Qc*peWshVjn8yUqiDa6t-"
  no_reply: "ztna-noreply@seifert.dev"

rate_limits:
  global:
    window_minutes: 1
    max_requests: 100
  auth:
    window_minutes: 1
    max_requests: 100

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true
  allow_raw_resources: true