app:
  identity_provider_mode: "org"

branding:
  app_name: "Seifert"
  hide_auth_layout_footer: true

redis:
  host: "redis"
  port: 6379
  password: "bjmNzpymEFmc6f4UTXsmXdF5K"
  db: 0

flags:
  enable_redis: true