services:

  # Nginx Reverse Proxy - https://github.com/nginx/nginx
  nginx:
    image: nginx:1.29.7-alpine@sha256:e7257f1ef28ba17cf7c248cb8ccf6f0c6e0228ab9c315c152f9c203cd34cf6d1
    container_name: nginx
    # ToDo: Fixen der DependsOn
    #depends_on:
    #  paperless:
    #    condition: service_healthy
    env_file: /opt/docker/secrets.env
    environment:
      - NGINX_ENVSUBST_FILTERED_VAR_NAMES=SECRET_DOMAIN SECRET_CERT_NAME
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/templates:/etc/nginx/templates:ro
      - /opt/docker/nginx/includes:/etc/nginx/includes:ro
      - /opt/docker/certbot/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Certbot - https://github.com/cloudflare/certbot-dns-cloudflare
  certbot:
    image: certbot/dns-cloudflare:v5.4.0@sha256:587d1d445ab308fb897af923f8ea570ba278445fd64a335303a65fe2a81d209c
    container_name: certbot
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file: /opt/docker/secrets.env
    environment:
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/certbot/certs:/etc/letsencrypt
      - /opt/docker/certbot/cloudflare.ini:/cloudflare.ini:ro
      - /opt/docker/certbot/certbot-entrypoint.sh:/entrypoint.sh:ro
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "openssl x509 -checkend 86400 -noout -in /etc/letsencrypt/live/${SECRET_CERT_NAME}/fullchain.pem || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    logging: *default-logging

  # Paperless
  paperless:
    container_name: paperless
    image: paperlessngx/paperless-ngx:2.20.13@sha256:4b05bcd28e6923768000b5d247cbf2c66fd49bdc3f3b05955bd4f6790a638b01
    depends_on:
      - database
      - redis
      - gotenberg
      - tika
    volumes:
      - /opt/docker/paperless/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - /mnt/paperless/export:/usr/src/paperless/export
      - /mnt/paperless/import:/usr/src/paperless/consume
    env_file: /opt/docker/secrets.env
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_FILENAME_FORMAT: "{{correspondent}}/{{ created_year }}/{{title}}"
      PAPERLESS_DBHOST: database
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_MAIL: ${PAPERLESS_ADMIN_MAIL}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 2
      PAPERLESS_WEBSERVER_WORKERS: 2
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${PAPERLESS_CSRF_TRUSTED_ORIGINS}
      PAPERLESS_CORS_ALLOWED_HOSTS: ${PAPERLESS_CORS_ALLOWED_HOSTS}
      PAPERLESS_TRUSTED_PROXIES: 172.16.10.6,172.16.66.10
      PAPERLESS_USE_X_FORWARD_HOST: true
      PAPERLESS_USE_X_FORWARD_PORT: true
      PAPERLESS_CONSUMER_POLLING: 10
      PAPERLESS_EMAIL_HOST: ${PAPERLESS_EMAIL_HOST}
      PAPERLESS_EMAIL_PORT: 587
      PAPERLESS_EMAIL_HOST_USER: ${PAPERLESS_EMAIL_HOST_USER}
      PAPERLESS_EMAIL_HOST_PASSWORD: ${PAPERLESS_EMAIL_HOST_PASSWORD}
      PAPERLESS_EMAIL_FROM: ${PAPERLESS_EMAIL_FROM}
      PAPLERESS_EMAIL_USE_TLS: true
      USERMAP_UID: 3002
      USERMAP_GID: 3003
    expose:
      - 8000
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging: *default-logging

  # Redis Cache
  redis:
    container_name: redis
    image: redis:8.6.2-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    volumes:
      - redisdata:/data
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging

  # Postgres-DB for Paperless
  database:
    container_name: database
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    volumes:
      - pgdata18:/var/lib/postgresql
    env_file: /opt/docker/secrets.env
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_BACKUP_SCHEDULE: "0 3 * * *"
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless -d paperless"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    logging: *default-logging

  # Gotenberg for Paperless
  gotenberg:
    image: gotenberg/gotenberg:8.29.1@sha256:36c925776fa0db0fd1030408d131fde7ac3453027a559883555155b72adb16a7
    container_name: gotenberg
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging

  # Tika for Paperless
  tika:
    image: apache/tika:3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
    container_name: tika
    networks:
      - localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging
  
  # Crowdsec AppSec for Paperless
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.6@sha256:63b595fef92de1778573b375897a45dd226637ee9a3d3db9f57ac7355c369493
    container_name: crowdsec
    networks:
      - localhost
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      TZ: Europe/Berlin
      ENROLL_TAGS: docker
      GID: "1000"
      DISABLE_LOCAL_API: true
      LOCAL_API_URL: ${CROWDSEC_LAPI_URL}                   # Crowdsec Central LAPI URL https://example.com:8443
      AGENT_USERNAME: ${CROWDSEC_LAPI_USERNAME}             # Crowdsec Maschine Username
      AGENT_PASSWORD: ${CROWDSEC_LAPI_KEY}             # Crowdsec Maschine Password
      COLLECTIONS: crowdsecurity/linux crowdsecurity/nginx crowdsecurity/base-http-scenarios andreasbrett/paperless-ngx
      PARSERS: crowdsecurity/whitelists
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
    logging: *default-logging

volumes:
  pgdata18:
  redisdata:

networks:
    localhost:
        name: localhost
        external: true