services:

 # Config Generator for Traefik
  traefik-config-generator:
    image: alpine:3.24
    container_name: traefik-config-generator
    restart: always
    labels:
      - "autoheal=true"
    env_file:
      - /opt/docker/secrets.env
    volumes:
      - /opt/docker/traefik/config/dynamic/:/mnt/config/
    command: >
      sh -c "apk add --no-cache gettext >/dev/null && 
              find /mnt/config/dynamic -type f -name '*.template' | while read -r template; do
                output=\"\${template%.template}\" &&
                envsubst < \"\$template\" > \"\$output\" &&
                chown 1000:1000 \"\$output\";
              done &&
              echo 'Alle dynamischen Configs generiert, schlafe jetzt...' &&
              sleep infinity"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /mnt/config/dynamic_config.yml ] || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    image: traefik:v3.7.4
    container_name: traefik
    restart: unless-stopped
    labels:
      - "autoheal=true"
    depends_on:
      crowdsec:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      traefik-config-generator:
        condition: service_healthy
    network_mode: service:gerbil
    env_file: /opt/docker/secrets.env
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/docker/traefik/config/traefik_config.yml:/etc/traefik/traefik_config.yml
      - /opt/docker/traefik/config/dynamic:/etc/traefik/dynamic
      - /opt/docker/traefik/config/sites/captcha.html:/etc/traefik/sites/captcha.html
      - /opt/docker/traefik/config/sites/ban.html:/etc/traefik/sites/ban.html
      - /opt/docker/traefik/geoblock:/var/lib/geoblock
      - /var/log/traefik:/var/log/traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    logging: *default-logging
  
  redis-cache:
    image: redis:8.8.0-alpine
    container_name: redis-cache
    restart: unless-stopped
    labels:
      - "autoheal=true"
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    logging: *default-logging

  cloudflared:
    image: cloudflare/cloudflared:2026.6.0
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - proxy-net
    # --no-tls-verify erlaubt cloudflared, dem selbstsignierten HTTPS-Zertifikat von Traefik zu vertrauen
    command: tunnel --no-autoupdate run --no-tls-verify
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    logging: *default-logging

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8
    container_name: crowdsec
    restart: unless-stopped
    labels:
      - "autoheal=true"
    env_file: /opt/docker/secrets.env
    environment:
      DISABLE_LOCAL_API: true
      LOCAL_API_URL: ${CROWDSEC_LAPI_URL}                   # Crowdsec Central LAPI URL https://example.com:8443
      AGENT_USERNAME: ${CROWDSEC_LAPI_USERNAME}             # Crowdsec Maschine Username
      AGENT_PASSWORD: ${CROWDSEC_LAPI_KEY}             # Crowdsec Maschine Password
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      ENROLL_TAGS: docker
      GID: "1000"
      PARSERS: crowdsecurity/whitelists
    volumes:
      - /opt/docker/crowdsec/config:/etc/crowdsec
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7422/ || [ $? -ne 7 ]"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging: *default-logging

  auto-heal:
    image: willfarrell/autoheal:1.2.0
    container_name: auto-heal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 300
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 1000M

networks:
  proxy-net:
    name: proxy-net
    external: false