services:
  # Nginx Reverse Proxy - https://github.com/nginx/nginx
  nginx:
    image: nginx:1.31.2-alpine
    container_name: nginx
    env_file: /opt/docker/secrets.env
    #depends_on:
    #  lldap:
    #    condition: service_healthy
    #  pocket-id:
    #    condition: service_healthy
    environment:
      - NGINX_ENVSUBST_FILTERED_VAR_NAMES=SECRET_DOMAIN SECRET_CERT_NAME
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/templates:/etc/nginx/templates:ro
      - /opt/docker/nginx/includes:/etc/nginx/includes:ro
      - /opt/docker/certbot/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
      - "636:636"
    networks:
      - auth-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging: &default-logging # default logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Certbot - https://github.com/cloudflare/certbot-dns-cloudflare
  certbot:
    image: certbot/dns-cloudflare:v5.6.0
    container_name: certbot
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file: /opt/docker/secrets.env
    environment:
      - SECRET_CERT_NAME=${SECRET_CERT_NAME}
    volumes:
      - /opt/docker/certbot/certs:/etc/letsencrypt
      - /opt/docker/certbot/cloudflare.ini:/cloudflare.ini:ro
      - /opt/docker/certbot/certbot-entrypoint.sh:/entrypoint.sh:ro
    networks:
      - auth-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "openssl x509 -checkend 86400 -noout -in /etc/letsencrypt/live/${SECRET_CERT_NAME}/fullchain.pem || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    logging: *default-logging
  
  # LLDAP - https://github.com/lldap/lldap
  lldap:
    image: ghcr.io/lldap/lldap:v0.6.3-alpine
    container_name: lldap
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_LDAP_BASE_DN=dc=seifert,dc=dev
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER=${SMTP_SERVER} # The SMTP server address, e.g. smtp.example.com
      - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp provider's documentation for this setting
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      - LLDAP_SMTP_OPTIONS__USER=${SMTP_USER} # The SMTP user, usually your email address
      - LLDAP_SMTP_OPTIONS__PASSWORD=${SMTP_PASSWORD} # The SMTP password
      - LLDAP_SMTP_OPTIONS__FROM=${SMTP_FROM} # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      - LLDAP_SMTP_OPTIONS__TO=${SMTP_TO} # Same for reply-to, optional.
      - LLDAP_HTTP_URL=${LLDAP_HTTP_URL} # URL used in the email template to compose the reset link
    volumes:
      - /opt/docker/lldap:/data
    networks:
      - auth-net
    ports:
      - "389:3890"
    healthcheck:
      test: ["CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging: *default-logging
  
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.9.0
    container_name: pocket-id
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      ENCRYPTION_KEY_FILE: /app/encryption.key
      APP_URL: https://auth.${SECRET_DOMAIN}
      TRUST_PROXY: true
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      PUID: 1000
      PGID: 1000
      ANALYTICS_DISABLED: true
      VERSION_CHECK_DISABLED: true
    networks:
      - auth-net
    volumes:
      - "/opt/docker/pocket-id/data:/app/data"
      - "/opt/docker/pocket-id/encryption.key:/app/encryption.key:ro"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    logging:
      driver: "journald"
      options:
        tag: "pocket-id"

  # Crowdsec - Engine & AppSec Only - https://github.com/crowdsecurity/crowdsec
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8@sha256:2f527c9bb8b367120eb08b82890aa912ce96bfa1ada93dda0721700e4b4e0dde
    container_name: crowdsec
    networks:
      - auth-net
    restart: unless-stopped
    env_file: /opt/docker/secrets.env
    environment:
      ENROLL_TAGS: docker
      GID: "1000"
      DISABLE_LOCAL_API: true
      LOCAL_API_URL: ${CROWDSEC_LAPI_URL}              # Crowdsec Central LAPI URL https://example.com:8443
      AGENT_USERNAME: ${CROWDSEC_LAPI_USERNAME}        # Crowdsec Maschine Username
      AGENT_PASSWORD: ${CROWDSEC_LAPI_KEY}             # Crowdsec Maschine Password
      COLLECTIONS: crowdsecurity/linux crowdsecurity/nginx crowdsecurity/base-http-scenarios LePresidente/authelia
      PARSERS: crowdsecurity/whitelists
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
      - /opt/docker/crowdsec/config:/etc/crowdsec
    logging: *default-logging

networks:
  auth-net:
    name: auth-net
    external: false